name: 🔄 Sync Workflow


on:
  workflow_dispatch:
    inputs:
      workoutsToDownload:
        type: number
        default: "5"
      saveLocalCopy:
        type: boolean
        default: false
  schedule:
    - cron: '0 1 * * *'

env:
  OUTPUT_DIR: /app/output

jobs:
  sync:
    name: 🔁 Sync
    runs-on: ubuntu-latest
    container:
      image: philosowaffle/peloton-to-garmin
      options: --user root
    steps:
      - name: 📁 Create output directory
        run: mkdir -p ${{ env.OUTPUT_DIR }}

      - name: 📝 Create config file
        env:
          DEFAULT_WORKOUT_NUM: 5
        run: |
          cat <<EOT > /app/configuration.json
          {
            "App": {
              "EnablePolling": false,
              "CheckForUpdates": true,
              "CloseConsoleOnFinish": true
            },
            "Format": {
              "Fit": true,
              "Json": false,
              "Tcx": false,
              "SaveLocalCopy": ${{ github.event.inputs.saveLocalCopy || false }},
              "IncludeTimeInHRZones": true,
              "IncludeTimeInPowerZones": true,
              "StackedWorkouts": {
                "AutomaticallyStackWorkouts": false,
                "MaxAllowedGapSeconds": 60
              }
            },
            "Peloton": {
              "NumWorkoutsToDownload": ${{ github.event.inputs.workoutsToDownload || env.DEFAULT_WORKOUT_NUM }}
            },
            "Garmin": {
              "Upload": true,
              "FormatToUpload": "fit"
            },
            "Observability": {
              "Prometheus": {
                "Enabled": false
              },
              "Jaeger": {
                "Enabled": false
              },
              "Serilog": {
                "Using": [ "Serilog.Sinks.Console" ],
                "MinimumLevel": "Information"
              }
            }
          }
          EOT

      - name: ▶️ Run P2G Sync
        run: /app/ConsoleClient
        if: ${{ env.P2G_PELOTON__EMAIL && env.P2G_PELOTON__PASSWORD && env.P2G_GARMIN__EMAIL && env.P2G_GARMIN__PASSWORD }}
        working-directory: /app
        env:
          P2G_PELOTON__EMAIL: ${{ secrets.PELOTON_USERNAME }}
          P2G_PELOTON__PASSWORD: ${{ secrets.PELOTON_PASSWORD }}
          P2G_GARMIN__EMAIL: ${{ secrets.GARMIN_USERNAME }}
          P2G_GARMIN__PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
          TZ: America/Chicago

      - name: ⤴️ Upload output directory
        uses: actions/upload-artifact@v3
        if: ${{ github.event.inputs.saveLocalCopy }}
        with:
          name: output
          path: ${{ env.OUTPUT_DIR }}
          if-no-files-found: error
